/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.pejic.zavrsnirad.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pejić
 */
public class GlavniProzor extends javax.swing.JFrame {

    /**
     * Creates new form GlavniProzor
     */
    public GlavniProzor() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);

        try {

            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException e) {

        }
        setTitle("Kuharica");
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("Slike" + File.separator + "kuhanje.jpg").getImage().getScaledInstance(220, 282, Image.SCALE_DEFAULT));
        lblSlika.setIcon(imageIcon);
        hyperLinks();
        mniOsoba.setIcon(new ImageIcon(new ImageIcon("Slike" + File.separator + "osobe.jpg").getImage().getScaledInstance(20, 15, Image.SCALE_DEFAULT)));
        mniAlergen.setIcon(new ImageIcon(new ImageIcon("Slike" + File.separator + "alergija.jpg").getImage().getScaledInstance(20, 15, Image.SCALE_DEFAULT)));
        mniRecept.setIcon(new ImageIcon(new ImageIcon("Slike" + File.separator + "recept.jpg").getImage().getScaledInstance(20, 15, Image.SCALE_DEFAULT)));
        mniIzlaz.setIcon(new ImageIcon(new ImageIcon("Slike" + File.separator + "izlaz.jpg").getImage().getScaledInstance(20, 15, Image.SCALE_DEFAULT)));
        mniSastojak.setIcon(new ImageIcon(new ImageIcon("Slike" + File.separator + "sastojci.jpg").getImage().getScaledInstance(20, 15, Image.SCALE_DEFAULT)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSlika = new javax.swing.JLabel();
        lblLink1 = new javax.swing.JLabel();
        lblLink2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniOsoba = new javax.swing.JMenuItem();
        mniAlergen = new javax.swing.JMenuItem();
        mniSastojak = new javax.swing.JMenuItem();
        mniRecept = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblLink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLink1MouseClicked(evt);
            }
        });

        lblLink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLink2MouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        mniOsoba.setText("Osobe");
        mniOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOsobaActionPerformed(evt);
            }
        });
        jMenu1.add(mniOsoba);

        mniAlergen.setText("Alergeni");
        mniAlergen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlergenActionPerformed(evt);
            }
        });
        jMenu1.add(mniAlergen);

        mniSastojak.setText("Sastojci");
        mniSastojak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSastojakActionPerformed(evt);
            }
        });
        jMenu1.add(mniSastojak);

        mniRecept.setText("Recepti");
        mniRecept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReceptActionPerformed(evt);
            }
        });
        jMenu1.add(mniRecept);
        jMenu1.add(jSeparator1);

        mniIzlaz.setText("Izlaz");
        jMenu1.add(mniIzlaz);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLink2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLink1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLink1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLink2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLink1MouseClicked

        try {
            Desktop.getDesktop().browse(new URI("https://www.healthline.com/nutrition/50-super-healthy-foods"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(lblLink1, "Nije moguć pristup stranici");
        }

    }//GEN-LAST:event_lblLink1MouseClicked

    private void lblLink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLink2MouseClicked
        try {
            Desktop.getDesktop().browse(new URI("https://acaai.org/allergies/types/food-allergy"));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Nije moguć pristup stranici");
        }
    }//GEN-LAST:event_lblLink2MouseClicked

    private void mniOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOsobaActionPerformed
        new OsobaProzor().setVisible(true);
    }//GEN-LAST:event_mniOsobaActionPerformed

    private void mniAlergenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlergenActionPerformed
        new AlergenProzor().setVisible(true);
    }//GEN-LAST:event_mniAlergenActionPerformed

    private void mniSastojakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSastojakActionPerformed
        new SastojakProzor().setVisible(true);
    }//GEN-LAST:event_mniSastojakActionPerformed

    private void mniReceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReceptActionPerformed
        new ReceptProzor().setVisible(true);
    }//GEN-LAST:event_mniReceptActionPerformed

    private void hyperLinks() {

        lblLink1.setForeground(Color.BLUE.darker());
        lblLink1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblLink1.setText("<html><a href=''>Eat healthy stay healthy</a></html>");
        lblLink1.setToolTipText("50 Foods that are super healthy");

        lblLink2.setForeground(Color.BLUE.darker());
        lblLink2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblLink2.setText("<html><a href=''>Stay one step ahead</a></html>");
        lblLink2.setToolTipText("Food Allergy, what you need to know");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblLink1;
    private javax.swing.JLabel lblLink2;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JMenuItem mniAlergen;
    private javax.swing.JMenuItem mniIzlaz;
    private javax.swing.JMenuItem mniOsoba;
    private javax.swing.JMenuItem mniRecept;
    private javax.swing.JMenuItem mniSastojak;
    // End of variables declaration//GEN-END:variables
}
