/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.pejic.zavrsnirad.view;

import hr.pejic.zavrsnirad.controller.ObradaRecept;
import hr.pejic.zavrsnirad.model.Recept;
import hr.pejic.zavrsnirad.utility.Iznimka;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import hr.pejic.zavrsnirad.utility.BrisanjePoruke;
import javax.swing.DefaultListModel;

/**
 *
 * @author Pejić
 */
public class ReceptProzor extends javax.swing.JFrame {

    private final ObradaRecept or;
    private Recept recept;
    /**
     * Creates new form ReceptProzor
     */
    public ReceptProzor() {
        initComponents();
        or = new ObradaRecept();
        setTitle(Recept.class.getSimpleName());
        ucitajRecepte();
        lblIkona.setText("\ud83d\udd0d");
    }
    
    private void ucitajRecepte(){
        DefaultListModel<Recept> m = new DefaultListModel<>();
        or.ispis().forEach(r -> m.addElement(r));
        lstReceptiUBazi.setModel(m);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked") 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReceptiUBazi = new javax.swing.JList<>();
        pnlObrada = new javax.swing.JPanel();
        btnRadioKreiraj = new javax.swing.JRadioButton();
        btnRadioIzmjena = new javax.swing.JRadioButton();
        btnRadioBrisanje = new javax.swing.JRadioButton();
        btnObrada = new javax.swing.JButton();
        lblIznimka = new javax.swing.JLabel();
        txtTraziRecept = new javax.swing.JTextField();
        lblIkona = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recepti"));

        lstReceptiUBazi.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstReceptiUBaziValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstReceptiUBazi);

        pnlObrada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGrupa.add(btnRadioKreiraj);
        btnRadioKreiraj.setText("Kreiraj");
        btnRadioKreiraj.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                recept = new Recept();
                recept.setNaziv(txtNaziv.getText());
                or.setEntitet(recept);
                try{
                    or.kreiraj();
                    ucitajRecepte();
                    lblIznimka.setText("<html>Recept "+recept.getNaziv()+"<br> je uspjepšno kreiran");
                    new BrisanjePoruke(lblIznimka).start();
                }catch(Iznimka ex){
                    lblIznimka.setText(ex.getPoruka());
                }

            }
        });

        btnGrupa.add(btnRadioIzmjena);
        btnRadioIzmjena.setText("Izmjena");
        btnRadioIzmjena.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                recept = lstReceptiUBazi.getSelectedValue();
                if(recept==null){
                    lblIznimka.setText("<html>Odaberite recept<br>za izmjenu");
                    return;
                }
                String naziv = recept.getNaziv();
                recept.setNaziv(txtNaziv.getText());
                or.setEntitet(recept);
                try{
                    or.azuriraj();
                    lblIznimka.setText("<html>Recept "+naziv+"<br>je uspjepšno<br>ažuriran u "+recept.getNaziv());
                    ucitajRecepte();
                    new BrisanjePoruke(lblIznimka).start();
                }catch(Iznimka ex){
                    lblIznimka.setText(ex.getPoruka());
                }

            }
        });

        btnGrupa.add(btnRadioBrisanje);
        btnRadioBrisanje.setText("Brisanje");
        btnRadioBrisanje.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                recept = lstReceptiUBazi.getSelectedValue();
                if(recept==null){
                    lblIznimka.setText("<html>Odaberite recept<br>za brisanje");
                    return;
                }
                String naziv = recept.getNaziv();
                or.setEntitet(recept);
                try{
                    or.obrisi();
                    lblIznimka.setText("<html>Recept "+naziv+"<br>je uspjepšno<br>obrisan");
                    ucitajRecepte();
                    new BrisanjePoruke(lblIznimka).start();
                }catch(Iznimka ex){
                    lblIznimka.setText(ex.getPoruka());
                }

            }
        });

        btnObrada.setText("Obrada");
        btnObrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlObradaLayout = new javax.swing.GroupLayout(pnlObrada);
        pnlObrada.setLayout(pnlObradaLayout);
        pnlObradaLayout.setHorizontalGroup(
            pnlObradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObradaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlObradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRadioIzmjena)
                    .addComponent(btnRadioBrisanje)
                    .addComponent(btnRadioKreiraj)
                    .addComponent(btnObrada, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnlObradaLayout.setVerticalGroup(
            pnlObradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlObradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRadioKreiraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadioIzmjena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRadioBrisanje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblIznimka.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblIkona.setText("Icon");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIkona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTraziRecept, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlObrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIznimka, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlObrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIznimka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTraziRecept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIkona))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstReceptiUBaziValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstReceptiUBaziValueChanged
             
        recept = lstReceptiUBazi.getSelectedValue();
        if(recept==null){
            return;
        }
        txtNaziv.setText(recept.getNaziv());                
        
    }//GEN-LAST:event_lstReceptiUBaziValueChanged

    private void btnObradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObradaActionPerformed
           lblIznimka.setText("<html>Hvala na stečenome<br> znanju! :D");
    }//GEN-LAST:event_btnObradaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrupa;
    private javax.swing.JButton btnObrada;
    private javax.swing.JRadioButton btnRadioBrisanje;
    private javax.swing.JRadioButton btnRadioIzmjena;
    private javax.swing.JRadioButton btnRadioKreiraj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIkona;
    private javax.swing.JLabel lblIznimka;
    private javax.swing.JList<Recept> lstReceptiUBazi;
    private javax.swing.JPanel pnlObrada;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtTraziRecept;
    // End of variables declaration//GEN-END:variables
}
