/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.peji.zavrsnirad.view;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Pejić
 */
public class GlavniProzor extends javax.swing.JFrame {

    /**
     * Creates new form GlavniProzor
     */
    public GlavniProzor() {
        initComponents();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon("Slike/kuhanje.jpg").getImage().getScaledInstance(150, 400, Image.SCALE_DEFAULT));
        lblSlika.setIcon(imageIcon);
        lblSlika.getSize();
                
                ImageIcon slika = new ImageIcon("Slike/kuhanje.jpg");
               // slika.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSlika = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mniOsoba = new javax.swing.JMenuItem();
        mniAlergen = new javax.swing.JMenuItem();
        mniSastojak = new javax.swing.JMenuItem();
        mniRecept = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniIzlaz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");

        mniOsoba.setText("Osobe");
        jMenu1.add(mniOsoba);

        mniAlergen.setText("Alergeni");
        jMenu1.add(mniAlergen);

        mniSastojak.setText("Sastojci");
        jMenu1.add(mniSastojak);

        mniRecept.setText("Recepti");
        jMenu1.add(mniRecept);
        jMenu1.add(jSeparator1);

        mniIzlaz.setText("Izlaz");
        jMenu1.add(mniIzlaz);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JMenuItem mniAlergen;
    private javax.swing.JMenuItem mniIzlaz;
    private javax.swing.JMenuItem mniOsoba;
    private javax.swing.JMenuItem mniRecept;
    private javax.swing.JMenuItem mniSastojak;
    // End of variables declaration//GEN-END:variables
}
